### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by l0rd** [ansibleplaybookbundle/eclipse-che-apb#23]
CI is fails as soon as the command `ansible-playbook` in the APB image is run: 

![image](https://user-images.githubusercontent.com/606959/44098754-4c1d530a-9fe1-11e8-9b44-07458686ce1e.png)

**Comment by l0rd** [comment]
We should be able to reproduce this problem locally following these instructions https://github.com/ansibleplaybookbundle/eclipse-che-apb#cli-testing

**Comment by ibuziuk** [comment]
Eugene figured out that in the latest apb-base the way of passing extra-vars has been changed and now should be done via json e.g. -e "{"namespace": "${APB_NAME}"}" . The build should be fixed by his new PR with tls and external keycloak / postgree https://github.com/ansibleplaybookbundle/eclipse-che-apb/pull/24. In the meantime, I have opened an issue for apb-base since the 
 help is still saying that  setting vars via `key=value` is a valid option https://github.com/ansibleplaybookbundle/apb-base/issues/46

**Comment by ghost** [comment]
@ibuziuk this PR https://github.com/ansibleplaybookbundle/eclipse-che-apb/pull/24 will require json format anyway, since this is the only way to pass booleans [according to docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#passing-variables-on-the-command-line)

**Comment by ghost** [comment]
Fixed CI in https://github.com/ansibleplaybookbundle/eclipse-che-apb/pull/24
I decided to make lint rules not so strict, and move test commands to a dedicated script to avoid yaml formatting issues in `.travis.yaml`
